export const ADMIN_ROUTES = {
  LOGIN: '/admin/login',
  DASHBOARD: '/admin',
  USERS: '/admin/users',
  STAFF: '/admin/staff',
  TRAINS: '/admin/trains',
  ROUTES: '/admin/routes',
  SCHEDULES: '/admin/schedules',
  STATIONS: '/admin/stations',
  PLATFORMS: '/admin/platforms',
  COACHES: '/admin/coaches',
  SEATS: '/admin/seats',
  FARES: '/admin/fares',
  QUOTAS: '/admin/quotas',
  BOOKINGS: '/admin/bookings',
  TDR: '/admin/tdr',
  FINES: '/admin/fines',
  INCIDENTS: '/admin/incidents',
  GRIEVANCES: '/admin/grievances',
  REPORTS: '/admin/reports',
  AUDIT_LOGS: '/admin/audit-logs',
  NOTIFICATIONS: '/admin/notifications',
  SETTINGS: '/admin/settings',
} as const;
